language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anu26/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true anu26/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-create"
  env: "DockerCreate-env"
  bucket_name: "elasticbeanstalk-us-east-2-401155515458"
  bucket_path: "docker-create"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

